spring:
  data:
    rest:
      base-path: /data-api
  security:
    user:
      name: buzz
      password: 123
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    generate-unique-name: false
    name: tacocloud
  kafka:
    template:
      default-topic: tacocloud.orders.topic
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
#  rabbitmq:
#    template:
#      exchange: tacocloud.order
#      routing-key: kitchens.central
#      receive-timeout: 30000
#  jms:
#    template:
#      default-destination: tacocloud.order.queue

taco:
  orders:
    pageSize: 10